-- Migration: 0014_fix_app_archetype_constraint
-- 1. Drop the outdated check constraint on apps.app_archetype.
-- 2. Ensure all existing data is migrated to the new vocabulary.
-- 3. Add a new check constraint with the unified vocabulary.

-- Drop the old constraint (default name generated by Postgres)
ALTER TABLE apps DROP CONSTRAINT IF EXISTS apps_app_archetype_check;

-- Ensure data is migrated (matches 0013_admin_ui.sql but safer to repeat here)
UPDATE apps
  SET app_archetype = CASE app_archetype
    WHEN 'storefront_ui'  THEN 'storefront_backend'
    WHEN 'backend_only'   THEN 'backend'
    ELSE app_archetype
  END
WHERE app_archetype IN ('storefront_ui', 'backend_only');

-- Add the new constraint
ALTER TABLE apps
  ADD CONSTRAINT apps_app_archetype_check
  CHECK (app_archetype IN ('storefront_backend', 'storefront_backend_admin', 'backend'));
